### PR TITLE
BUG fix and misc updates

### PR DESCRIPTION
**Pull request by GitHubDragonFly**

### CODE REVIEW

**Comment by TheFern2** [comment]
Trying to test this, I've never used html with flask, would you mind commenting how to test the html template? I thought it would show up when doing a request, but I just see the json responses.

**Comment by GitHubDragonFly** [comment]
That html file is only for use with tables.

If, for example, you set "returnTable = True" inside the get_all_tags function then only the tag listing page will be shown inside the table and the other pages will still be a json response only. If you set that same value in all 3 functions then all of them will be shown inside the table.

**Comment by TheFern2** [comment]
Thanks for the PR, and the bug fixes. I appreciate all the hard work with the html. I ended up moving the template, and app.py with html stuff to its own branch. I would like to keep the main branch just for the api endpoints.

**Comment by GitHubDragonFly** [comment]
Smart move.

If anybody might ever ask for a table view then you have a branch to point them to.

**Pull request merged**
